import Head from "next/head";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { FormProvider } from "~/components/FormContext";
import Input from "~/components/input";

import Step1 from "~/components/Step1";
import Step2 from "~/components/Step2";

export default function Home() {
  const [step, setStep] = useState(1);

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm();

  const nextPage = (e, data) => {
    e.preventDefault();
    setStep((prevStep) => prevStep + 1);
    console.log(data);
  };
  return (
    <>
      <FormProvider>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gray-300">
          <form onSubmit={(e) => handleSubmit(nextPage(e))}>
            {step === 1 && <Step1 />}
            {step === 2 && <Step2 />}
          </form>
        </main>
      </FormProvider>
    </>
  );
}
